/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as BancosRouteImport } from './routes/bancos'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as CatalogosRouteImport } from './routes/catalogos'
import { Route as ConsolidadoRouteImport } from './routes/consolidado'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ErogacionesRouteImport } from './routes/erogaciones'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as ParametrosRouteImport } from './routes/parametros'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProyeccionRouteImport } from './routes/proyeccion'
import { Route as UsuariosUsuarioIdRouteImport } from './routes/usuarios.$usuarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const BancosRoute = BancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosRoute = CatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidadoRoute = ConsolidadoRouteImport.update({
  id: '/consolidado',
  path: '/consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ErogacionesRoute = ErogacionesRouteImport.update({
  id: '/erogaciones',
  path: '/erogaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametrosRoute = ParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyeccionRoute = ProyeccionRouteImport.update({
  id: '/proyeccion',
  path: '/proyeccion',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosUsuarioIdRoute = UsuariosUsuarioIdRouteImport.update({
  id: '/usuarios/$usuarioId',
  path: '/usuarios/$usuarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/bancos': typeof BancosRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogos': typeof CatalogosRoute
  '/consolidado': typeof ConsolidadoRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/importar': typeof ImportarRoute
  '/pagos': typeof PagosRoute
  '/parametros': typeof ParametrosRoute
  '/pedidos': typeof PedidosRoute
  '/proyeccion': typeof ProyeccionRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/bancos': typeof BancosRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogos': typeof CatalogosRoute
  '/consolidado': typeof ConsolidadoRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/importar': typeof ImportarRoute
  '/pagos': typeof PagosRoute
  '/parametros': typeof ParametrosRoute
  '/pedidos': typeof PedidosRoute
  '/proyeccion': typeof ProyeccionRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/bancos': typeof BancosRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogos': typeof CatalogosRoute
  '/consolidado': typeof ConsolidadoRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/importar': typeof ImportarRoute
  '/pagos': typeof PagosRoute
  '/parametros': typeof ParametrosRoute
  '/pedidos': typeof PedidosRoute
  '/proyeccion': typeof ProyeccionRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/bancos'
    | '/bitacora'
    | '/catalogos'
    | '/consolidado'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/importar'
    | '/pagos'
    | '/parametros'
    | '/pedidos'
    | '/proyeccion'
    | '/usuarios/$usuarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/bancos'
    | '/bitacora'
    | '/catalogos'
    | '/consolidado'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/importar'
    | '/pagos'
    | '/parametros'
    | '/pedidos'
    | '/proyeccion'
    | '/usuarios/$usuarioId'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/bancos'
    | '/bitacora'
    | '/catalogos'
    | '/consolidado'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/importar'
    | '/pagos'
    | '/parametros'
    | '/pedidos'
    | '/proyeccion'
    | '/usuarios/$usuarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  BancosRoute: typeof BancosRoute
  BitacoraRoute: typeof BitacoraRoute
  CatalogosRoute: typeof CatalogosRoute
  ConsolidadoRoute: typeof ConsolidadoRoute
  ContratosRoute: typeof ContratosRoute
  ErogacionesRoute: typeof ErogacionesRoute
  FacturasRoute: typeof FacturasRoute
  ImportarRoute: typeof ImportarRoute
  PagosRoute: typeof PagosRoute
  ParametrosRoute: typeof ParametrosRoute
  PedidosRoute: typeof PedidosRoute
  ProyeccionRoute: typeof ProyeccionRoute
  UsuariosUsuarioIdRoute: typeof UsuariosUsuarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bancos': {
      id: '/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof BancosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos': {
      id: '/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof CatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidado': {
      id: '/consolidado'
      path: '/consolidado'
      fullPath: '/consolidado'
      preLoaderRoute: typeof ConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erogaciones': {
      id: '/erogaciones'
      path: '/erogaciones'
      fullPath: '/erogaciones'
      preLoaderRoute: typeof ErogacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametros': {
      id: '/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof ParametrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyeccion': {
      id: '/proyeccion'
      path: '/proyeccion'
      fullPath: '/proyeccion'
      preLoaderRoute: typeof ProyeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/$usuarioId': {
      id: '/usuarios/$usuarioId'
      path: '/usuarios/$usuarioId'
      fullPath: '/usuarios/$usuarioId'
      preLoaderRoute: typeof UsuariosUsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  BancosRoute: BancosRoute,
  BitacoraRoute: BitacoraRoute,
  CatalogosRoute: CatalogosRoute,
  ConsolidadoRoute: ConsolidadoRoute,
  ContratosRoute: ContratosRoute,
  ErogacionesRoute: ErogacionesRoute,
  FacturasRoute: FacturasRoute,
  ImportarRoute: ImportarRoute,
  PagosRoute: PagosRoute,
  ParametrosRoute: ParametrosRoute,
  PedidosRoute: PedidosRoute,
  ProyeccionRoute: ProyeccionRoute,
  UsuariosUsuarioIdRoute: UsuariosUsuarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
