/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BancosRouteImport } from './routes/bancos'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ErogacionesRouteImport } from './routes/erogaciones'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as ProyeccionRouteImport } from './routes/proyeccion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BancosRoute = BancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ErogacionesRoute = ErogacionesRouteImport.update({
  id: '/erogaciones',
  path: '/erogaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyeccionRoute = ProyeccionRouteImport.update({
  id: '/proyeccion',
  path: '/proyeccion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bancos': typeof BancosRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/pagos': typeof PagosRoute
  '/proyeccion': typeof ProyeccionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bancos': typeof BancosRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/pagos': typeof PagosRoute
  '/proyeccion': typeof ProyeccionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bancos': typeof BancosRoute
  '/contratos': typeof ContratosRoute
  '/erogaciones': typeof ErogacionesRoute
  '/facturas': typeof FacturasRoute
  '/pagos': typeof PagosRoute
  '/proyeccion': typeof ProyeccionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bancos'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/pagos'
    | '/proyeccion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bancos'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/pagos'
    | '/proyeccion'
  id:
    | '__root__'
    | '/'
    | '/bancos'
    | '/contratos'
    | '/erogaciones'
    | '/facturas'
    | '/pagos'
    | '/proyeccion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BancosRoute: typeof BancosRoute
  ContratosRoute: typeof ContratosRoute
  ErogacionesRoute: typeof ErogacionesRoute
  FacturasRoute: typeof FacturasRoute
  PagosRoute: typeof PagosRoute
  ProyeccionRoute: typeof ProyeccionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bancos': {
      id: '/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof BancosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erogaciones': {
      id: '/erogaciones'
      path: '/erogaciones'
      fullPath: '/erogaciones'
      preLoaderRoute: typeof ErogacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyeccion': {
      id: '/proyeccion'
      path: '/proyeccion'
      fullPath: '/proyeccion'
      preLoaderRoute: typeof ProyeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BancosRoute: BancosRoute,
  ContratosRoute: ContratosRoute,
  ErogacionesRoute: ErogacionesRoute,
  FacturasRoute: FacturasRoute,
  PagosRoute: PagosRoute,
  ProyeccionRoute: ProyeccionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
